import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { generateFragment } from "../../bin/cli/fragment";
import { knownManifests } from "../../bin/tests/manifests";

/**
 * The locks fragment only has an effect if Caddy imports it, and only in the
 * blocks that serve previews. This test therefore re-reads the repository's
 * configuration: a deleted import line, one moved into the wrong block or
 * turned into a named import, would open every preview without anything
 * flagging it, generation carrying on producing a correct fragment.
 */

const ROOT = join(import.meta.dir, "..", "..");
const IMPORT_LOCKS = "import /etc/caddy/locks/*.caddy";

function read(path: string): string {
  return readFileSync(join(ROOT, path), "utf8");
}

/**
 * Extracts the body of the block whose header is given, by counting braces.
 * Comment lines are set aside before the count: they happily quote braces, and
 * they take no part in the structure.
 */
function block(text: string, header: string): string {
  const lines = text.split("\n");
  const start = lines.findIndex((line) => line.trimStart().startsWith(header));
  if (start === -1) throw new Error(`block not found: ${header}`);

  const body: string[] = [];
  let depth = 0;

  for (const line of lines.slice(start)) {
    const code = line.trimStart().startsWith("#") ? "" : line;
    depth += (code.match(/\{/g) ?? []).length - (code.match(/\}/g) ?? []).length;
    body.push(line);
    if (depth === 0 && body.length > 1) break;
  }

  return body.join("\n");
}

describe("infra/caddy/Caddyfile", () => {
  const caddyfile = read("infra/caddy/Caddyfile");

  test("imports the locks from the previews block", () => {
    expect(block(caddyfile, "*.{$SITESOLIDE_ZONE} {")).toInclude(IMPORT_LOCKS);
  });

  test("the import is a glob, never a named file", () => {
    // A named import of an absent file makes the entire adaptation fail, so
    // every site on the machine; a glob with no match is only a warning. The
    // folder is empty as long as no site is locked, which is the normal state.
    for (const line of caddyfile.split("\n")) {
      if (!line.includes("/etc/caddy/locks")) continue;
      expect(line.trim()).toBe(IMPORT_LOCKS);
    }
    expect(caddyfile).toInclude("/etc/caddy/locks/*.caddy");
  });

  test("does not import the locks in the blocks that serve final domains", () => {
    // A lock on the client's domain would close their site in production.
    expect(block(caddyfile, "{$SITESOLIDE_ZONE}, www.{$SITESOLIDE_ZONE} {")).not.toInclude("/etc/caddy/locks");
    expect(block(caddyfile, "https:// {")).not.toInclude("/etc/caddy/locks");
  });
});

/**
 * The same two constraints hold for any application project, not only for the
 * one that existed the day the lock was written. The next one will be
 * generated by `bin/sitesolide.ts`: a test naming it would not have covered
 * it, and its owner would have discovered the hole in production.
 */
/**
 * The blocks a deployment installs, generated as it generates them, from every
 * manifest the workstation knows: the platform's own and the neighbouring
 * sites' repository. No copy of a deployed block is kept anywhere to re-read,
 * and a fresh install still has the platform's own manifests to check.
 */
const APPS: [string, string][] = knownManifests()
  .map((manifest): [string, string | null] => [manifest.slug, generateFragment(manifest)])
  .filter((pair): pair is [string, string] => pair[1] !== null);

test("no generated block escapes the tests below", () => {
  // Failing which a path mistake would make the loop empty, therefore always
  // green, and the constraints would no longer be checked anywhere.
  expect(APPS.length).toBeGreaterThan(0);
});

/**
 * The header of the preview block, as this fragment writes it.
 *
 * `<slug>.{$SITESOLIDE_ZONE} {`: a block never names the zone.
 */
function previewHeader(file: string, slug: string): string {
  const header = file
    .split("\n")
    .find((line) => line.startsWith(`${slug}.`) && line.trimEnd().endsWith(" {"));
  if (header === undefined) throw new Error(`preview block not found for ${slug}`);
  return header.trimEnd();
}

describe.each(APPS)("generated block: %s", (slug, file) => {
  const PREVIEW = previewHeader(file, slug);

  test("imports the locks in the preview block", () => {
    // This block is more specific than the zone's wildcard and goes ahead of
    // it: without this import, the application site would be the only one
    // unable to lock itself, and bin/lock.sh enable would fail on its 401
    // check.
    expect(block(file, PREVIEW)).toInclude(IMPORT_LOCKS);
  });

  test("imports the locks in no other block", () => {
    // A lock on the final domain would close the client's site in production.
    // Only the preview block is allowed to import it.
    const preview = block(file, PREVIEW);
    const elsewhere = file.split(preview).join("");
    expect(elsewhere).not.toInclude("/etc/caddy/locks");
  });

  test("the site routes use no handle", () => {
    // Measured in the lab: all the handles of a single block form one
    // exclusive group. The lock's handle won, its right cookie branch left the
    // group with no response written, and the site's handles were already set
    // aside: the visitor holding the right code received a 200 with an empty
    // body. reverse_proxy and file_server, for their part, form no group.
    const routes = block(file, `(${slug}-routes) {`);
    for (const line of routes.split("\n")) {
      if (line.trimStart().startsWith("#")) continue;
      expect(line).not.toInclude("handle");
    }
    expect(routes).toInclude("file_server");
  });
});
