import { afterEach, describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  buildTable,
  isValidDomain,
  domainForms,
  MANIFEST_NAME,
  render,
  isValidSlug,
} from "../src/table";

const temporary: string[] = [];

/** Reproduces a /srv/sites tree: one folder per site, its manifest inside. */
function sites(manifestes: Record<string, string | null>): string {
  const root = mkdtempSync(join(tmpdir(), "sitesolide-sites-"));
  temporary.push(root);

  for (const [slug, content] of Object.entries(manifestes)) {
    mkdirSync(join(root, slug), { recursive: true });
    if (content !== null) writeFileSync(join(root, slug, MANIFEST_NAME), content);
  }
  return root;
}

/** A domain declared the way the manifest writes it, `sitesolide.json` abridged. */
function domain(name: string, active = true, aliases?: string[]): string {
  return JSON.stringify({ slug: "x", domain: { name, active, ...(aliases ? { aliases } : {}) } });
}

afterEach(() => {
  while (temporary.length > 0) rmSync(temporary.pop()!, { recursive: true, force: true });
});

describe("buildTable", () => {
  test("keeps an active site, with its www form", () => {
    const root = sites({ agency: domain("sample-agency.example") });
    expect([...buildTable(root)]).toEqual([
      ["sample-agency.example", "agency"],
      ["www.sample-agency.example", "agency"],
    ]);
  });

  test("ignores a site that is inactive, without a domain, or without a manifest", () => {
    // These three cases describe a site still in preview: it must not appear
    // in the table, therefore must not obtain a certificate.
    const root = sites({
      not_yet: domain("future.test", false),
      no_domain: '{"slug":"no_domain"}',
      preview: null,
    });
    expect(buildTable(root).size).toBe(0);
  });

  test("stops on a site.json left over from before the switch", () => {
    // The most dangerous case of the migration: the manifest has not gone up
    // onto the VM yet, the old descriptor is still there. Ignoring it would
    // drop the client's domain out of the table, therefore out of Caddy and out
    // of its certificate renewal, without a word.
    const root = sites({ agency: null });
    writeFileSync(join(root, "agency", "site.json"), '{"domain":"sample-agency.example","actif":true}');
    expect(() => buildTable(root)).toThrow(/sitesolide deploy/);
  });

  test("keeps the declared aliases", () => {
    const root = sites({ agency: domain("new.test", true, ["old.test"]) });
    expect([...buildTable(root).keys()].sort()).toEqual([
      "new.test",
      "old.test",
      "www.new.test",
      "www.old.test",
    ]);
  });

  test("does not add a www to a domain that is already a subdomain", () => {
    const root = sites({ agency: domain("shop.example.test") });
    expect([...buildTable(root).keys()]).toEqual(["shop.example.test"]);
  });

  test("refuses to let two sites claim the same domain", () => {
    // Without this guard, the last folder read would win silently, and one
    // client would serve another one's site.
    const root = sites({
      agency: domain("sample-agency.example"),
      studio: domain("sample-agency.example"),
    });
    expect(() => buildTable(root)).toThrow(/claimed/);
  });

  test("refuses a syntactically invalid domain", () => {
    const root = sites({ agency: domain("not a domain") });
    expect(() => buildTable(root)).toThrow(/invalid domain/);
  });

  test("refuses an unreadable manifest rather than ignoring it", () => {
    const root = sites({ agency: "{ this is not json" });
    expect(() => buildTable(root)).toThrow(/unreadable/);
  });

  test("normalizes the case and the trailing dot of a declared domain", () => {
    const root = sites({ agency: domain("Sample-Agency.EXAMPLE.") });
    expect(buildTable(root).has("sample-agency.example")).toBe(true);
  });
});

describe("render", () => {
  test("produces indented lines, sorted, preceded by a warning", () => {
    const rendered = render(new Map([["b.test", "studio"], ["a.test", "agency"]]));
    const lines = rendered.split("\n");
    expect(lines[0]).toBe("# Generated by api/scripts/generate-domains.ts, do not edit by hand.");
    expect(lines.slice(1)).toEqual(["\ta.test agency", "\tb.test studio"]);
  });

  test("stays valid when no client has a domain", () => {
    // Caddy imports this file: empty, it must stay syntactically correct.
    expect(render(new Map()).split("\n")).toHaveLength(1);
  });
});

describe("naming guards", () => {
  test("isValidSlug refuses what could escape /srv/sites", () => {
    expect(isValidSlug("agency")).toBe(true);
    expect(isValidSlug("..")).toBe(false);
    expect(isValidSlug("../etc")).toBe(false);
    expect(isValidSlug("/absolute")).toBe(false);
  });

  test("isValidDomain follows the shape of a domain name", () => {
    expect(isValidDomain("sample-agency.example")).toBe(true);
    expect(isValidDomain("a.b.c.test")).toBe(true);
    expect(isValidDomain("nodot")).toBe(false);
    expect(isValidDomain("-dash-at-the-start.test")).toBe(false);
    expect(isValidDomain("space .test")).toBe(false);
  });

  test("domainForms only adds www at the second level", () => {
    expect(domainForms("example.test")).toEqual(["example.test", "www.example.test"]);
    expect(domainForms("a.example.test")).toEqual(["a.example.test"]);
  });
});
