import { describe, expect, test } from "bun:test";
import { certificateTargets, projectUnits, readDomainTable, servedTargets, siteFolders } from "../src/hosts";

const ZONE = "test-zone.invalid";

describe("what the machine serves", () => {
  test("the directories that are sites: slugs and the landing's, nothing else", () => {
    expect(siteFolders(["cms", ZONE, "lost+found", "Shop", "a.b", "-x", "portal", "cms"], ZONE)).toEqual([
      "cms",
      "portal",
      ZONE,
    ]);
  });

  test("the domain table, as bin/generate-domains.sh writes it, read without trusting it", () => {
    const table = [
      "# Generated by api/scripts/generate-domains.ts, do not edit",
      "\tsample-agency.example cms",
      "\twww.sample-agency.example cms",
      "\tShop.Example shop",
      "\tnot a domain at all",
      "\tlonely.example",
      "\tunder_score.example shop",
      "",
    ].join("\n");
    expect(readDomainTable(table)).toEqual([
      ["sample-agency.example", "cms"],
      ["www.sample-agency.example", "cms"],
      ["shop.example", "shop"],
    ]);
    expect(readDomainTable(null)).toEqual([]);
  });

  test("the bare domain and www first, then each preview, then each customer domain", () => {
    const targets = servedTargets(ZONE, ["cms", "shop", ZONE], [
      ["sample-agency.example", "cms"],
      ["gone.example", "removed"],
      [`stray.${ZONE}`, "cms"],
    ]);
    expect(targets).toEqual([
      { host: ZONE, slug: ZONE },
      { host: `www.${ZONE}`, slug: ZONE },
      { host: `cms.${ZONE}`, slug: "cms" },
      { host: `shop.${ZONE}`, slug: "shop" },
      { host: "sample-agency.example", slug: "cms" },
      { host: "gone.example", slug: null },
    ]);
  });

  test("the bare domain is probed even with no landing directory: Caddy serves it all the same", () => {
    expect(servedTargets(ZONE, ["cms"], []).slice(0, 2)).toEqual([
      { host: ZONE, slug: null },
      { host: `www.${ZONE}`, slug: null },
    ]);
  });

  test("one certificate read per certificate: the wildcard once, the bare domain, each customer domain", () => {
    const targets = servedTargets(ZONE, ["cms", "shop", ZONE], [["sample-agency.example", "cms"]]);
    expect(certificateTargets(ZONE, targets)).toEqual([
      { id: `certificate:${ZONE}`, label: ZONE, sni: ZONE, slug: ZONE },
      { id: `certificate:*.${ZONE}`, label: `*.${ZONE}`, sni: `cms.${ZONE}`, slug: null },
      { id: "certificate:sample-agency.example", label: "sample-agency.example", sni: "sample-agency.example", slug: "cms" },
    ]);
  });

  test("with no preview, the wildcard is read through www, under the same name", () => {
    const certificates = certificateTargets(ZONE, servedTargets(ZONE, [], []));
    expect(certificates[1]).toEqual({ id: `certificate:*.${ZONE}`, label: `*.${ZONE}`, sni: `www.${ZONE}`, slug: null });
  });

  test("each project's main unit, the landing's under its own name", () => {
    expect([...projectUnits(["cms", ZONE], ZONE)]).toEqual([
      ["cms", "cms"],
      ["sitesolide-landing", ZONE],
    ]);
  });
});
