#!/usr/bin/env bun
/**
 * The machine's reading, written once a minute under root's identity.
 *
 * It is this project's only privileged component, and it is deliberately
 * stupid: it reads, it writes a JSON, it interprets nothing. All the judgement
 * belongs to `src/state.ts`, which the unprivileged service runs at display
 * time. A display rule that changes is then fixed by an ordinary `sitesolide
 * deploy`, without touching what runs as root.
 *
 * Why this detour rather than a direct reading by the web service:
 *
 *   - the unit generated by `bin/cli/unit.ts` confines every project, `/srv`
 *     replaced by an empty mount where only its own directories are exposed
 *     again, and that file says at the top that nothing is taken out of it;
 *   - `/etc/caddy/locks-codes.json` is in 0600 for the deployment account. A
 *     mount does not get around Unix permissions: a privileged reader is
 *     needed for the lock codes either way.
 *
 * Each path comes from an environment variable, none is hard-coded: the
 * collector is launched that way on the workstation, on a test tree, like the
 * lock generator.
 *
 *   SITES_DIR=/tmp/attempt/srv STATE_FILE=/tmp/state.json OWNER= bun collector.ts
 */
import { existsSync, readFileSync, readdirSync, renameSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { $ } from "bun";
import { hostTable } from "./src/audience";
import { unitOf, type Raw, type RawFolder, type RawMachine, type RawUnit } from "./src/state";

const SITES_DIR = process.env.SITES_DIR ?? "/srv/sites";
const CODES_FILE = process.env.CODES_FILE ?? "/etc/caddy/locks-codes.json";
const DOMAINS_FILE = process.env.DOMAINS_FILE ?? "/etc/caddy/domaines.map";
const BLOCKS_DIR = process.env.BLOCKS_FOLDER ?? "/etc/caddy/sites";
const STATE_FILE = process.env.STATE_FILE ?? "/srv/sites/dashboard/data/state.json";

/**
 * The snapshot the `analytics` service drops, and the host table it is given
 * back in exchange.
 *
 * These two files are the only exchange between the two services, and it goes
 * through no network: `analytics` cannot reach the dashboard, the dashboard
 * cannot open its database, and the loopback rule reserves their ports to Caddy
 * and to root. The collector, already privileged and already passing every
 * minute, carries both in the direction that suits.
 */
const AUDIENCE_FILE =
  process.env.AUDIENCE_FILE ?? "/srv/sites/analytics/data/instantane.json";
const HOSTS_FILE = process.env.HOSTS_FILE ?? "/srv/sites/analytics/data/hotes.json";
const HOSTS_OWNER = process.env.HOSTS_OWNER ?? "site-analytics:site-analytics";
const ZONE = requiredZone();

/**
 * The zone served, which the dashboard turns into each site's address and on
 * which the host table handed to `analytics` is built.
 *
 * NO DEFAULT NAMES A MACHINE. A ready made zone here would be the one of this
 * file's author: an installation elsewhere would display his addresses, and
 * the host table would let his domains through instead of the ones of the
 * machine it runs on. The collector therefore stops rather than guess.
 *
 * The value comes from the workstation's configuration, written by `sitesolide
 * init`, and reaches the machine through the unit's environment, as it does
 * for the shared service.
 */
function requiredZone(): string {
  const zone = process.env.SITESOLIDE_ZONE ?? "";
  if (zone !== "") return zone;

  console.error("collector: SITESOLIDE_ZONE is missing, and no zone is assumed here");
  console.error('declare the zone with "sitesolide init", then deploy again');
  process.exit(1);
}

/**
 * The owner of the file written. Empty, the chown is skipped: a test on the
 * workstation has no site-dashboard account.
 */
const OWNER = process.env.OWNER ?? "site-dashboard:site-dashboard";

/** The manifest's name, the only configuration file dropped beside a site. */
const MANIFEST_NAME = "sitesolide.json";

/** What `systemctl show` must return, and nothing more. */
const PROPERTIES = [
  "LoadState",
  "ActiveState",
  "SubState",
  "MemoryCurrent",
  "MemoryPeak",
  "MemoryMax",
  "NRestarts",
  "ActiveEnterTimestamp",
  // Processor time accumulated since the unit started. systemd gives no CPU
  // level: the rate is computed between two readings, in src/state.ts.
  "CPUUsageNSec",
];

/**
 * A reading that fails returns null: an incomplete reading is worth more than
 * none.
 *
 * `incomplete` distinguishes the file that does not exist from the one that could
 * not be read, and the nuance matters: `/etc/caddy/locks-codes.json` does not
 * exist as long as no preview has ever been closed, which is a normal state.
 * Confusing it with a failed reading would make an alarm show on a perfectly
 * healthy machine.
 */
async function text(path: string, incomplete: string | null = null): Promise<string | null> {
  const file = Bun.file(path);
  try {
    if (!(await file.exists())) return incomplete;
    return await file.text();
  } catch {
    return null;
  }
}

/**
 * `--timestamp=unix` is not cosmetic: without it systemd returns a date spelled
 * out in full, in the machine's time zone and language, which would have to be
 * parsed again for a less certain result. See src/state.ts#readTimestamp.
 */
async function readUnit(name: string): Promise<RawUnit | null> {
  const arguments_ = ["show", name, "--timestamp=unix", ...PROPERTIES.flatMap((p) => ["-p", p])];
  const output = await $`systemctl ${arguments_}`.nothrow().quiet();
  if (output.exitCode !== 0) return null;

  const properties: RawUnit = {};
  for (const line of output.stdout.toString().split("\n")) {
    const separator = line.indexOf("=");
    if (separator === -1) continue;
    properties[line.slice(0, separator)] = line.slice(separator + 1);
  }
  return properties;
}

/**
 * The size of the directory in bytes. `-x` so as not to cross a mount point:
 * this figure is read every minute, and the collector's unit already pays for
 * it in Nice and in IOSchedulingClass=idle.
 */
async function folderBytes(folder: string): Promise<number | null> {
  const output = await $`du -sxb ${folder}`.nothrow().quiet();
  if (output.exitCode !== 0) return null;
  const value = Number(output.stdout.toString().split(/\s+/)[0]);
  return Number.isFinite(value) ? value : null;
}

/** The ports listening on the loopback, to confront with the declared port. */
async function ports(): Promise<number[]> {
  const output = await $`ss -ltnH`.nothrow().quiet();
  if (output.exitCode !== 0) return [];

  const found = new Set<number>();
  for (const line of output.stdout.toString().split("\n")) {
    const columns = line.trim().split(/\s+/);
    // With no header, the local address is the fourth column: State Recv-Q
    // Send-Q Local:Port Peer:Port.
    const address = columns[3];
    if (address === undefined) continue;

    // The loopback alone. Without this filter, 22, 80 and 443 went into the
    // list and a project that declared one of them would pass for listening
    // when it is ssh or Caddy that answers.
    const host = address.slice(0, address.lastIndexOf(":"));
    if (host !== "127.0.0.1" && host !== "[::1]") continue;

    const port = Number(address.slice(address.lastIndexOf(":") + 1));
    if (Number.isInteger(port)) found.add(port);
  }
  return [...found].sort((a, b) => a - b);
}

/**
 * The fragments in service, one file per app project, content included.
 *
 * The content and not a boolean: it is src/state.ts that decides what must be
 * read in it, today the portal's door. The privileged component stays as stupid
 * as possible, and a rule that changes is fixed by an ordinary deployment,
 * without touching what runs as root.
 */
function readBlocks(): Record<string, string> {
  const found: Record<string, string> = {};
  try {
    for (const name of readdirSync(BLOCKS_DIR).sort()) {
      if (!name.endsWith(".caddy")) continue;
      const slug = name.slice(0, -".caddy".length);
      try {
        found[slug] = readFileSync(join(BLOCKS_DIR, name), "utf8");
      } catch {
        // An unreadable fragment is not a missing fragment: the empty string
        // says so, and src/state.ts will see it with no door rather than gone.
        found[slug] = "";
      }
    }
  } catch {
    return {};
  }
  return found;
}

async function readMachine(): Promise<RawMachine | null> {
  const memory = await $`free -b`.nothrow().quiet();
  const disk = await $`df -B1 --output=size,avail ${SITES_DIR}`.nothrow().quiet();
  const cores = await $`nproc`.nothrow().quiet();

  // Three averages, then the tasks and the last PID, which we do nothing with.
  //
  // readFileSync and not Bun.file: procfs announces a size of zero bytes, and a
  // reading that trusts it returns an empty string. Measured on 31 August 2026,
  // where load1 was a perfectly false zero, Number("") being zero, while
  // load5 and load15 were null for want of a second and third field.
  let loads: string[] = [];
  try {
    loads = readFileSync("/proc/loadavg", "utf8").trim().split(/\s+/);
  } catch {
    loads = [];
  }

  const memoryLine = memory.stdout.toString().split("\n")[1]?.trim().split(/\s+/) ?? [];
  const diskLine = disk.stdout.toString().split("\n")[1]?.trim().split(/\s+/) ?? [];

  // The empty string is refused explicitly: Number("") is zero, and a zero that
  // comes from a failed reading is worse than an absence, since it is displayed
  // as a measurement.
  const integer = (raw: string | undefined): number | null => {
    if (raw === undefined || raw.trim() === "") return null;
    const value = Number(raw);
    return Number.isFinite(value) ? value : null;
  };

  const decimalOf = (raw: string | undefined): number | null => {
    if (raw === undefined || raw.trim() === "") return null;
    const value = Number(raw);
    return Number.isFinite(value) ? value : null;
  };

  return {
    load1: decimalOf(loads[0]),
    load5: decimalOf(loads[1]),
    load15: decimalOf(loads[2]),
    cores: integer(cores.stdout.toString().trim()),
    memoryTotal: integer(memoryLine[1]),
    // free's "available" column, the only one that says what one more service
    // could take: "free" ignores the cache, reclaimable at any moment.
    memoryAvailable: integer(memoryLine[6]),
    diskTotal: integer(diskLine[0]),
    diskFree: integer(diskLine[1]),
  };
}

/**
 * What must be kept from the previous reading to compute a CPU rate: its date
 * and each unit's counter. The file that is about to be replaced is the only
 * place where that state lives, which saves the collector from holding one of
 * its own: it is launched afresh every minute by the timer, and therefore has
 * no memory between two passes.
 *
 * A file that is missing, truncated or from an earlier version returns null,
 * and the rates are then displayed as blanks instead of lying.
 */
async function previousReading(): Promise<Raw["previous"]> {
  const content = await text(STATE_FILE);
  if (content === null) return null;

  try {
    const previousRaw = JSON.parse(content) as Raw;
    if (typeof previousRaw.generated !== "number" || !Array.isArray(previousRaw.folders)) return null;

    const cpu: Record<string, number> = {};
    for (const folder of previousRaw.folders) {
      const raw = folder.unit?.CPUUsageNSec;
      if (raw === undefined) continue;
      const value = Number(raw);
      if (Number.isFinite(value)) cpu[folder.slug] = value;
    }
    return { generated: previousRaw.generated, cpu };
  } catch {
    return null;
  }
}

async function collect(): Promise<Raw> {
  const folders: RawFolder[] = [];

  for (const entry of readdirSync(SITES_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const root = join(SITES_DIR, entry.name);
    const manifest = join(root, MANIFEST_NAME);

    let deployed: number | null = null;
    try {
      deployed = Math.round(statSync(manifest).mtimeMs);
    } catch {
      deployed = null;
    }

    folders.push({
      slug: entry.name,
      manifest: await text(manifest),
      unit: await readUnit(unitOf(entry.name)),
      bytes: await folderBytes(root),
      deployed,
    });
  }

  return {
    generated: Date.now(),
    zone: ZONE,
    folders,
    codes: await text(CODES_FILE, "{}"),
    domains: await text(DOMAINS_FILE),
    // Missing as long as `analytics` has not run once, which is a normal state:
    // the dashboard says so rather than showing an empty page.
    audience: await text(AUDIENCE_FILE),
    ports: await ports(),
    blocks: readBlocks(),
    machine: await readMachine(),
    previous: await previousReading(),
  };
}

/**
 * Writing through a temporary file then a rename, in the same directory: the
 * service reads this file on every request, and must never see half of it. The
 * permissions are set before the rename, so that there is no instant at which
 * the file is readable by others.
 */
async function writeSnapshot(raw: Raw): Promise<void> {
  const temp = `${STATE_FILE}.tmp`;
  await Bun.write(temp, `${JSON.stringify(raw)}\n`);
  await $`chmod 600 ${temp}`.nothrow().quiet();
  if (OWNER !== "") await $`chown ${OWNER} ${temp}`.nothrow().quiet();
  renameSync(temp, STATE_FILE);
}

/**
 * Drops the host table at `analytics`, which cannot build it.
 *
 * It is this collector's only write outside the dashboard's directory, and it
 * is declared as such in its unit. It carries no secret: the host to directory
 * correspondence is already read in the Caddyfile and in DNS. What it brings
 * `analytics` is the one thing it cannot know on its own, and without which it
 * refuses every measurement.
 *
 * The directory is not created if it is missing: `analytics` may not be
 * deployed on this machine, and putting a directory in its place would mask
 * that it is missing.
 */
async function writeHosts(raw: Raw): Promise<void> {
  const folder = dirname(HOSTS_FILE);
  if (!existsSync(folder)) return;

  const content = `${JSON.stringify({ generated: raw.generated, hosts: hostTable(raw) })}\n`;
  const temp = `${HOSTS_FILE}.tmp`;
  await Bun.write(temp, content);
  await $`chmod 640 ${temp}`.nothrow().quiet();
  if (HOSTS_OWNER !== "") await $`chown ${HOSTS_OWNER} ${temp}`.nothrow().quiet();
  renameSync(temp, HOSTS_FILE);
}

const raw = await collect();
await $`mkdir -p ${dirname(STATE_FILE)}`.nothrow().quiet();
await writeSnapshot(raw);
await writeHosts(raw);
console.log(`${raw.folders.length} folders collected → ${STATE_FILE}`);
