/** Local port of the shared service. See bin/cli/loopback.ts for the allocation. */
export const PORT = Number(process.env.PORT ?? 3001);

/**
 * Client domain table, generated by `bin/generate-domains.sh` from the
 * manifests dropped alongside the sites. Caddy uses it to route, this service
 * to authorize: the same file governs both, so no domain can be certified
 * without being routable, nor routable without being authorized.
 */
export const DOMAIN_TABLE_FILE = process.env.DOMAINS_FILE ?? "/etc/caddy/domaines.map";

/**
 * The table is re-read at most once per window. The endpoint is called during
 * the TLS handshake: it must never depend on a disk access on every request.
 */
export const DOMAIN_TABLE_TTL_MS = 10_000;

/**
 * Zone covered by the wildcard certificate, therefore barred from on demand
 * issuance.
 *
 * It comes from the environment, which the unit sets from the machine's
 * configuration. No default value: a ready made zone here would refuse someone
 * else's domains and let its own through. Empty, the rule does not apply, and
 * the domain table alone decides.
 */
export const MAIN_ZONE = process.env.SITESOLIDE_ZONE ?? "";

/** A refusal is logged only once per domain over this window. */
export const LOG_WINDOW_MS = 5 * 60 * 1000;

/** Beyond that, already logged domains are forgotten rather than kept in memory. */
export const MAX_LOGGED_DOMAINS = 500;
