import { describe, expect, test } from "bun:test";
import {
  buildAudience,
  pagesPerVisit,
  percentage,
  STALE_AFTER_MS,
  hostTable,
  averageTime,
  type AudienceSnapshot,
} from "../src/audience";
import type { Raw } from "../src/state";

/**
 * Two things are judged here, and nowhere else: the host table the collector
 * drops at `analytics`, which decides what that service agrees to write, and
 * the rates the dashboard displays.
 */
const folder = (slug: string) => ({
  slug,
  manifest: null,
  unit: null,
  bytes: null,
  deployed: null,
});

function rawOf(modifications: Partial<Raw> = {}): Raw {
  return {
    generated: Date.parse("2026-09-21T10:00:00Z"),
    zone: "test-zone.invalid",
    folders: [folder("vineyard"), folder("cms"), folder("test-zone.invalid")],
    codes: "{}",
    domains: null,
    ports: [],
    blocks: {},
    machine: null,
    previous: null,
    ...modifications,
  };
}

describe("hostTable", () => {
  test("gives every directory its preview subdomain", () => {
    // Caddy's wildcard block serves them by naming convention, with no
    // configuration: a deployed site is therefore measurable with nothing to do.
    const table = hostTable(rawOf());
    expect(table["vineyard.test-zone.invalid"]).toBe("vineyard");
    expect(table["cms.test-zone.invalid"]).toBe("cms");
  });

  test("gives the zone's directory the bare domain and its www", () => {
    // It is the repository's only asymmetric mapping: the landing is served
    // from /srv/sites/test-zone.invalid, never /srv/sites/landing.
    const table = hostTable(rawOf());
    expect(table["test-zone.invalid"]).toBe("test-zone.invalid");
    expect(table["www.test-zone.invalid"]).toBe("test-zone.invalid");
    // And above all not a subdomain of its own.
    expect(table["test-zone.invalid.test-zone.invalid"]).toBeUndefined();
  });

  test("adds the customers' own domains", () => {
    const table = hostTable(
      rawOf({
        domains: [
          "# Generated by api/scripts/generate-domains.ts, do not edit by hand.",
          "\tvineyard-modern.test vineyard",
          "\twww.vineyard-modern.test vineyard",
        ].join("\n"),
      }),
    );
    expect(table["vineyard-modern.test"]).toBe("vineyard");
    expect(table["www.vineyard-modern.test"]).toBe("vineyard");
  });

  test("skips a line it cannot read", () => {
    // The table is generated, but it is read back here without assuming it
    // was generated correctly: a truncated line must not make the following
    // ones be lost.
    const table = hostTable(
      rawOf({ domains: "\tincomplete\n\n\tvineyard-modern.test vineyard\n" }),
    );
    expect(table["vineyard-modern.test"]).toBe("vineyard");
    expect(Object.keys(table)).not.toContain("incomplete");
  });

  test("stores the domains in lower case", () => {
    // The host comes from the browser, which does not guarantee its case; the
    // comparison on the analytics side is exact.
    const table = hostTable(rawOf({ domains: "\tVineyard-Modern.TEST vineyard" }));
    expect(table["vineyard-modern.test"]).toBe("vineyard");
  });
});

describe("the rates", () => {
  test("percentage yields zero rather than NaN with no visit", () => {
    expect(percentage(0, 0)).toBe(0);
    expect(percentage(1, 4)).toBe(25);
  });

  test("pagesPerVisit yields one decimal", () => {
    expect(pagesPerVisit(851, 405)).toBe(2.1);
    expect(pagesPerVisit(0, 0)).toBe(0);
  });

  test("averageTime counts only the timed views", () => {
    // A browser closed outright sends no leave signal: counting those views
    // as zero would drag the average down for no reason.
    expect(averageTime(300, 4)).toBe(75);
    expect(averageTime(0, 0)).toBe(0);
  });
});

describe("buildAudience", () => {
  const NOW = Date.parse("2026-09-21T10:00:00Z");

  const snapshot: AudienceSnapshot = {
    generatedAt: NOW - 30_000,
    timeZone: "Europe/Paris",
    days: 30,
    from: "2026-08-23",
    to: "2026-09-21",
    sites: {
      "test-zone.invalid": {
        totals: { views: 851, visits: 405, bounces: 120, timedViews: 551, seconds: 46_284 },
        days: [{ day: "2026-09-21", views: 47, visits: 21 }],
        rankings: { path: [{ value: "/", total: 157 }] },
      },
    },
  };

  const with_ = (content: string | null) =>
    buildAudience(rawOf({ audience: content }), NOW);

  test("computes the rates at display time", () => {
    const site = with_(JSON.stringify(snapshot)).sites["test-zone.invalid"];
    expect(site?.views).toBe(851);
    expect(site?.bounceRate).toBe(30);
    expect(site?.pagesPerVisit).toBe(2.1);
    expect(site?.timePerPage).toBe(84);
  });

  test("says the age of what it shows", () => {
    const audience = with_(JSON.stringify(snapshot));
    expect(audience.present).toBe(true);
    expect(audience.age).toBe(30_000);
    expect(audience.stale).toBe(false);
  });

  test("flags a snapshot that is too old rather than keep quiet about it", () => {
    // The worst possible outcome would be a dashboard presenting last week's
    // photograph as today's numbers.
    const old = { ...snapshot, generatedAt: NOW - STALE_AFTER_MS - 1 };
    expect(with_(JSON.stringify(old)).stale).toBe(true);
  });

  test("copes with a reading that predates this measurement", () => {
    // A collector deployed before it does not carry that field: the dashboard
    // has to open all the same, in the minute that follows a deployment.
    expect(with_(null).present).toBe(false);
    expect(buildAudience(rawOf(), NOW).present).toBe(false);
  });

  test("copes with an unreadable snapshot", () => {
    expect(with_("{ this is not json").present).toBe(false);
    expect(with_("null").present).toBe(false);
    expect(with_("[]").present).toBe(false);
  });

  test("skips a site with no totals rather than yield NaNs", () => {
    const damaged = { ...snapshot, sites: { vineyard: {} as never } };
    expect(with_(JSON.stringify(damaged)).sites.vineyard).toBeUndefined();
  });
});
